export const ChatMessageTypes = {
  STATUS: 'status',
  ASSISTANT_START: 'assistant_start',
  DELTA: 'delta',
  ERROR: 'error',
  COMPLETE: 'complete',
  METADATA: 'metadata',
} as const;

export const ChatActionTypes = {
  CREATE_ORDER: 'CREATE_ORDER',
  DELETE_ORDER: 'DELETE_ORDER',
  UPDATE_ORDER: 'UPDATE_ORDER',
  ADD_ORDER_ITEM: 'ADD_ORDER_ITEM',
  DELETE_ORDER_ITEM: 'DELETE_ORDER_ITEM',
  UPDATE_ORDER_ITEM: 'UPDATE_ORDER_ITEM',
  VIEW_ACCOUNT: 'VIEW_ACCOUNT',
  VIEW_ORDER_DETAILS: 'VIEW_ORDER_DETAILS',
  VIEW_ORDERS: 'VIEW_ORDERS',
  VIEW_PRODUCT: 'VIEW_PRODUCT',
  VIEW_CONSUMER: 'VIEW_CONSUMER',
  WRITE_EMAIL: 'WRITE_EMAIL',
  SEND_EMAIL: 'SEND_EMAIL',
} as const;
