export const Roles = {
  SALES_REP: 'SALES_REP',
  ACCOUNT_MANAGER: 'ACCOUNT_MANAGER',
  TRADE_MARKETING: 'TRADE_MARKETING',
  FINANCE: 'FINANCE',
  COLLECTIONS: 'COLLECTIONS',
  LOGISTICS: 'LOGISTICS',
  ASSISTANT: 'assistant',
  USER: 'USER',
} as const;
